"""empty message

Revision ID: 0e3c7bdbdff6
Revises: 65929d5d1aa6
Create Date: 2026-08-13 08:43:11.136313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3c7bdbdff6'
down_revision = '65929d5d1aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor', schema=None) as batch_op:
        batch_op.alter_column('tag',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor', schema=None) as batch_op:
        batch_op.alter_column('tag',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
