"""empty message

Revision ID: 65929d5d1aa6
Revises: fb66cc9d3b4b
Create Date: 2026-08-12 07:47:33.245296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65929d5d1aa6'
down_revision = 'fb66cc9d3b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor', schema=None) as batch_op:
        batch_op.drop_column('tag')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
