"""empty message

Revision ID: 7a110b992913
Revises: 4210f1d2c325
Create Date: 2026-08-07 07:20:10.914517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a110b992913'
down_revision = '4210f1d2c325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_column('habit_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habit_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
