"""empty message

Revision ID: b83f36d015d0
Revises: a508d40a735d
Create Date: 2026-07-25 12:43:35.096586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83f36d015d0'
down_revision = 'a508d40a735d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:

        batch_op.drop_constraint("quest_pkey", type_="primary")

        batch_op.alter_column('title',
                              existing_type=sa.VARCHAR(length=20),
                              type_=sa.String(length=100),
                              existing_nullable=False)
        batch_op.alter_column('description',
                              existing_type=sa.VARCHAR(length=120),
                              type_=sa.String(length=500),
                              existing_nullable=False)
        batch_op.alter_column('status',
                              existing_type=sa.VARCHAR(length=250),
                              type_=sa.String(length=30),
                              existing_nullable=False)
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('habit_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.drop_constraint(batch_op.f(
            'quest_description_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('quest_title_key'), type_='unique')

        batch_op.create_primary_key("quest_pkey", ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:

        batch_op.drop_constraint("quest_pkey", type_="primary")
        batch_op.create_unique_constraint(batch_op.f('quest_title_key'), [
                                          'title'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('quest_description_key'), [
                                          'description'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('habit_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('status',
                              existing_type=sa.String(length=30),
                              type_=sa.VARCHAR(length=250),
                              existing_nullable=False)
        batch_op.alter_column('description',
                              existing_type=sa.String(length=500),
                              type_=sa.VARCHAR(length=120),
                              existing_nullable=False)
        batch_op.alter_column('title',
                              existing_type=sa.String(length=100),
                              type_=sa.VARCHAR(length=20),
                              existing_nullable=False)

        batch_op.create_primary_key(
            "quest_pkey", ["id", "user_id", "habit_id"])

    # ### end Alembic commands ###
