"""empty message


Revision ID: db4b22b0a33f
Revises: 
Create Date: 2026-08-05 12:45:25.451979



"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.


revision = 'db4b22b0a33f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('password', sa.String(
                        length=250), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('mentor',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('mentorname', sa.String(
                        length=20), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('password', sa.String(
                        length=250), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('mentorname')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=20), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('chat',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('mentor_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('habit',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(
                        length=500), nullable=False),
                    sa.Column('status', sa.String(length=30), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('quest',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(
                        length=500), nullable=False),
                    sa.Column('status', sa.String(length=30), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('habit_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('service',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(
                        length=500), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('mentor_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('chat_message',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=False),
                    sa.Column('sender', sa.String(length=20), nullable=False),
                    sa.Column('content', sa.String(
                        length=500), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('quest_tracking',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('quest_id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('comment', sa.String(
                        length=500), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest_tracking')
    op.drop_table('chat_message')
    op.drop_table('service')
    op.drop_table('quest')
    op.drop_table('habit')
    op.drop_table('chat')
    op.drop_table('user')
    op.drop_table('mentor')
    op.drop_table('admin')
    # ### end Alembic commands ###
