"""empty message

Revision ID: eb0dc9e636dd
Revises: a7b2b072dc3f
Create Date: 2026-08-10 10:42:36.802568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0dc9e636dd'
down_revision = 'a7b2b072dc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'is_reserved', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('is_reserved')

    # ### end Alembic commands ###
