"""add image_url to models

Revision ID: fb66cc9d3b4b
Revises: 74b0ca86f237
Create Date: 2026-08-11 18:37:23.722436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb66cc9d3b4b'
down_revision = '74b0ca86f237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
